### ISSUE TITLE
![Work Breakdown Structure Template](https://user-images.githubusercontent.com/113265186/192539783-82a9ff6c-39f1-446a-9c17-e3df86843987.png)

### ISSUE THREAD

**Issue by markllego** [llegomark/Kabataan#33]
![Work Breakdown Structure Template](https://user-images.githubusercontent.com/113265186/192539783-82a9ff6c-39f1-446a-9c17-e3df86843987.png)

_Originally posted by @Lizzie22Lopez in https://github.com/llegomark/Kabataan/discussions/19_

**Comment by Lizzie22Lopez** [comment]
[KABATAANph.pptx](https://github.com/llegomark/Kabataan/files/9687599/KABATAANph.pptx)

Final Powerpoint presentation - October 1, 2022
